on: 
  pull_request:
    types: [opened]
name: Azure Delete Resource ARM Bicep
jobs:

  Delete-Resources:

    runs-on: ubuntu-latest
    steps:
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Destroy Resources
    - name: destroy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./.github/workflows/delete-resources.bicep
        failOnStdErr: false