on: [push]
name: Azure ARM Bicep
jobs:
  Build-and-deploy:

    if: contains( github.event.pull_request.title, 'spinup')  
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./.github/workflows/azure-main.bicep
        parameters: 'storagePrefix=git storageSKU=Standard_LRS'
        failOnStdErr: false

  Delete-Resources:

    runs-on: ubuntu-latest
    steps:
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Display List
      run: dir -R
      shell: bash


      # Destroy Resources
    - name: destroy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./.github/workflows/delete-resources.json
        failOnStdErr: false