on: 
  pull_request:
    types: [ labeled ]


name: Azure ARM Bicep
jobs:
  Build-and-deploy:
    if: ${{github.event.pull_request.title.*.name == 'spinup'}}
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./.github/workflows/azure-main.bicep
        parameters: 'storagePrefix=git storageSKU=Standard_LRS'
        failOnStdErr: false

  Delete-Resources:
    if: ${{ github.event.label.name == 'destroy'}}
    runs-on: ubuntu-latest
    steps:
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
          # Checkout code
    - uses: actions/checkout@main

      # Destroy Resources
    - name: destroy
      uses: azure/arm-deploy@v1

      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./.github/workflows/delete-resources.bicep
        failOnStdErr: false
  
  Run-Script:
    runs-on: ubuntu-latest
    steps:
        # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
       # Checkout code
    - uses: actions/checkout@main
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Get-AzResourceGroup -Name ${{ secrets.AZURE_RG }} | Remove-AzResourceGroup -Force
        azPSVersion: "latest"

  