
on: 
  pull_request:
    types: [ opened,labeled ]

name: Azure deploy staging Bicep
jobs:
  Build-and-deploy:

    if: contains(github.event.pull_request.labels.*.name, 'staging-test')
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./.github/workflows/azure-main.bicep
        parameters: 'storagePrefix=git storageSKU=Standard_LRS'
        failOnStdErr: false
